name: Tag It

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wozniakpl/tag-it@v1
        id: tag-it
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-release: 'true'
          pre-release-command: 'npm version $NEW_VERSION --no-git-tag-version'
      - name: Set up Node.js
        if: steps.tag-it.outputs.new-tag != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Publish to VS Code Marketplace
        if: steps.tag-it.outputs.new-tag != ''
        run: |
          npm install -g yarn
          yarn global add @vscode/vsce
          yarn
          vsce package
          VSCE_PAT=${{ secrets.AZURE_PAT }} vsce publish
