name: Tag It

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wozniakpl/tag-it@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-release: 'true'
          pre-release-command: 'npm version $NEW_VERSION --no-git-tag-version'
